name: Build vercel preview

run-name: ${{github.repository}} is running

env:
  # Need to add secrets on the Github repository settings page
  # Both ORG_ID and PROJECT_ID are stored in the .vercel/project.json file
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
  VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
  VITE_SUPABASE_PROJECT_REF: ${{ secrets.VITE_SUPABASE_PROJECT_REF }}
  VITE_CLIENT_URL: ${{ secrets.VITE_CLIENT_URL }}
  VITE_SITE_KEY: ${{ secrets.VITE_SITE_KEY }}

on:
  push:
    branches:
      - 'main'

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Use actions/checkout@v4
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Pull Vercel Environment Information
        # Create a Vercel token on the Vercel account settings page
        run: vercel pull --yes --environment=preview --token="$VERCEL_TOKEN"

      - name: Build Project Artifacts
        run: vercel build --token="$VERCEL_TOKEN"

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token="$VERCEL_TOKEN"
